# Travis configuration file
# http://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7_with_system_site_packages"

# Install numpy and scipy to avoid the painful compilation
before_install:
  - pip install coveralls
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq python-numpy python-scipy

# Install fits_reduce...
install:
  - pip install .
# Run tests
script:
  - nosetests --with-coverage --cover-package=-pyneslab --cover-inclusive
after_success:
  - coveralls
